### ISSUE TITLE
Avoir la possibilité d'avoir un ratio de kebab

### ISSUE THREAD

**Issue by corentinlevet** [Nathn/KebaBot#4]
Avoir un ratio de kebab via la commande /ratio.
Exclure les week-ends si possible.
Ratio à faire entre la date du premier kebab et du dernier kebab.

Exemple:
J'ai mangé 2 kebabs sur 10 jours.
J'ai donc un ratio de 2/10 = 0.2 kebabs par jour.

**Comment by Nathn** [comment]
Fait ! https://github.com/Nathn/KebaBot/commit/7ad47cfb968438842f5e0d01aa2758b07c0471ec
